#!/usr/bin/env bash
set -euo pipefail

# Exported variable names (keep in sync with config/env.local.sh.example)
readonly VAR_REPO="WS_GIT_REPO_ROOT"
readonly VAR_WORKTREE="WS_GIT_WORKTREE_PATH"

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
TOOLKIT_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
CONFIG_DIR="$TOOLKIT_ROOT/config"
OUT_FILE="$CONFIG_DIR/env.local.sh"

default_repo() {
  if git rev-parse --show-toplevel >/dev/null 2>&1; then
    git rev-parse --show-toplevel
  else
    echo ""
  fi
}

trim_quotes() {
  local s=$1
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  if [[ ${#s} -ge 2 ]]; then
    if [[ ${s:0:1} == '"' && ${s: -1} == '"' ]]; then
      s="${s:1:-1}"
    elif [[ ${s:0:1} == "'" && ${s: -1} == "'" ]]; then
      s="${s:1:-1}"
    fi
  fi
  printf '%s\n' "$s"
}

validate_repo() {
  local path=$1
  [[ -d $path ]] || {
    echo "Not a directory: $path" >&2
    return 1
  }
  git -C "$path" rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
    echo "Not a Git repository (or not a work tree): $path" >&2
    return 1
  }
}

validate_worktree_path() {
  local path=$1
  [[ -d $path ]] || {
    echo "Not a directory: $path" >&2
    return 1
  }
}

warn_worktree_not_registered() {
  local repo=$1 wt=$2
  if git -C "$repo" worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $2}' | grep -Fxq "$wt"; then
    return 0
  fi
  echo "Note: worktree path is not listed in 'git -C \"$repo\" worktree list' (OK if not added yet)." >&2
}

read_with_default() {
  local prompt=$1
  local default=$2
  local line
  if [[ ${WS_UI_MODE:-} == dialog ]]; then
    if ! line=$(dialog --stdout --inputbox "$prompt" 12 80 "$default" 2>/dev/tty); then
      return 1
    fi
    if [[ -n $default && -z ${line//[[:space:]]/} ]]; then
      printf '%s\n' "$default"
    else
      trim_quotes "$line"
    fi
  elif [[ -n $default ]]; then
    read -r -p "$prompt [$default]: " line || true
    if [[ -z ${line//[[:space:]]/} ]]; then
      printf '%s\n' "$default"
    else
      trim_quotes "$line"
    fi
  else
    read -r -p "$prompt: " line || true
    trim_quotes "$line"
  fi
}

main() {
  mkdir -p "$CONFIG_DIR"

  local def_repo repo_path wt_path
  def_repo=$(default_repo)

  if ! repo_path=$(read_with_default "Main repository root (absolute path) + /Salesforce" "$def_repo"); then
    dialog --title "setup.sh" --msgbox "Setup cancelled. OK to return to the menu." 8 50 2>/dev/tty
    exit 0
  fi
  while [[ -z ${repo_path//[[:space:]]/} ]]; do
    if [[ ${WS_UI_MODE:-} == dialog ]]; then
      dialog --title "setup.sh" --msgbox "Repository path is required." 7 50 2>/dev/tty
    else
      echo "Repository path is required." >&2
    fi
    if ! repo_path=$(read_with_default "Main repository root (absolute path)" "$def_repo"); then
      dialog --title "setup.sh" --msgbox "Setup cancelled. OK to return to the menu." 8 50 2>/dev/tty
      exit 0
    fi
  done
  repo_path=$(cd "$repo_path" && pwd)

  if ! wt_path=$(read_with_default "Worktree directory (absolute path)" ""); then
    dialog --title "setup.sh" --msgbox "Setup cancelled. OK to return to the menu." 8 50 2>/dev/tty
    exit 0
  fi
  while [[ -z ${wt_path//[[:space:]]/} ]]; do
    if [[ ${WS_UI_MODE:-} == dialog ]]; then
      dialog --title "setup.sh" --msgbox "Worktree path is required." 7 50 2>/dev/tty
    else
      echo "Worktree path is required." >&2
    fi
    if ! wt_path=$(read_with_default "Worktree directory (absolute path)" ""); then
      dialog --title "setup.sh" --msgbox "Setup cancelled. OK to return to the menu." 8 50 2>/dev/tty
      exit 0
    fi
  done
  wt_path=$(cd "$wt_path" && pwd)

  if [[ ${WS_UI_MODE:-} == dialog ]]; then
    if ! validate_repo "$repo_path"; then
      dialog --title "setup.sh" --msgbox "Invalid repository. Check the path and run setup again from the menu." 10 70 2>/dev/tty
      exit 1
    fi
    if ! validate_worktree_path "$wt_path"; then
      dialog --title "setup.sh" --msgbox "Invalid worktree path. Check the path and run setup again from the menu." 10 70 2>/dev/tty
      exit 1
    fi
  else
    validate_repo "$repo_path" || exit 1
    validate_worktree_path "$wt_path" || exit 1
  fi
  warn_worktree_not_registered "$repo_path" "$wt_path"

  local tmp
  tmp=$(mktemp)
  {
    echo "# Generated by scripts/setup.sh — do not commit"
    echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "export ${VAR_REPO}=$(printf '%q' "$repo_path")"
    echo "export ${VAR_WORKTREE}=$(printf '%q' "$wt_path")"
  } >"$tmp"
  mv -f "$tmp" "$OUT_FILE"
  chmod 600 "$OUT_FILE" 2>/dev/null || true

  if [[ ${WS_UI_MODE:-} == dialog ]]; then
    local srcq
    srcq=$(printf '%q' "$OUT_FILE")
    dialog --title "setup.sh" --msgbox "Wrote $OUT_FILE

In a regular shell, load with:
  source $srcq" 12 80 2>/dev/tty
  else
    echo "Wrote $OUT_FILE"
    echo "Load in this shell: source $(printf '%q' "$OUT_FILE")"
  fi
}

main "$@"
